"""Add macro_snapshot table

Revision ID: 119468b7c4f7
Revises: 
Create Date: 2026-04-19 19:33:58.220077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119468b7c4f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('m2_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dr007_avg', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('bond_10y_yield', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('gdp_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pmi_manufacturing', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('industrial_prod_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growth_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('cpi_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppi_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('inflation_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('policy_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('fed_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('dxy_index', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('us_cn_spread', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('global_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('monetary_condition', sa.Enum('wide', 'neutral', 'tight', name='monetaryconditionenum'), nullable=True),
    sa.Column('credit_condition', sa.Enum('wide', 'neutral', 'tight', name='creditconditionenum'), nullable=True),
    sa.Column('quadrant', sa.Enum('wide_wide', 'wide_tight', 'tight_wide', 'tight_tight', name='quadrantenum'), nullable=True),
    sa.Column('macro_multiplier', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_macro_snapshot_date', ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_snapshot_snapshot_date'), ['snapshot_date'], unique=True)

    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_market_data_code_date')
    )
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_index('ix_market_data_code_date', ['ts_code', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_ts_code'), ['ts_code'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('concept_sectors', sa.Text(), nullable=True),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('ix_stocks_code', ['ts_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_ts_code'), ['ts_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_snapshot_snapshot_date'))
        batch_op.drop_index('ix_macro_snapshot_date')

    op.drop_table('macro_snapshot')
    with op.batch_alter_table('logics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logics_logic_id'))
        batch_op.drop_index('ix_logics_family')

    op.drop_table('logics')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_logic_id'))
        batch_op.drop_index('ix_events_logic_expire')

    op.drop_table('events')
    # ### end Alembic commands ###
