"""Event extraction service - Stage 2 of the pipeline."""

import json
import hashlib
import logging
from typing import List, Dict, Any, Optional
from datetime import date, datetime
from decimal import Decimal
from uuid import uuid4

from litellm import acompletion
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.database.connection import async_session_maker
from src.logic.models import LogicModel, EventModel, LogicDirection

logger = logging.getLogger(__name__)


class EventExtractionService:
    """Stage 2: Extract events from news using logic schema.

    This service takes news articles and an existing logic schema,
    then extracts specific events mapped to those logics.
    """

    SYSTEM_PROMPT = """你是一名 A 股事件提取专家。

给定逻辑 schema 和新闻文本，提取具体事件：

逻辑 schema:
{logic_schema_json}

新闻文本：
{news_text}

输出 JSON 格式：

{{
  "events": [
    {{
      "event_id": "<auto-generated>",
      "logic_id": "<匹配的 logic_id>",
      "event_date": "<YYYY-MM-DD>",
      "headline": "<事件标题，20-50 字>",
      "strength_raw": <0.0-1.0>,
      "validity_days": <有效期天数，默认 30>,
      "keywords": ["<关键词 1>", "<关键词 2>"]
    }}
  ]
}}

强度评分标准：
- 0.8-1.0: 国家级政策、重大技术突破、业绩翻倍
- 0.5-0.7: 行业级新闻、重要财报、大额订单
- 0.3-0.4: 媒体报道、分析师点评、常规新闻
- 0.1-0.2: 传闻、不确定性高的信息

注意：
1. 只提取与给定逻辑 schema 相关的事件
2. 如果新闻不涉及任何给定逻辑，返回空数组
3. 事件日期从新闻中推断，格式 YYYY-MM-DD
4. strength_raw 必须基于客观标准，不要过度自信

输出（仅 JSON，无其他文字）："""

    def __init__(self, model: str = "claude-sonnet-4-6"):
        self.model = model

    async def extract_events(
        self,
        news_text: str,
        logics: List[LogicModel],
        source: str = None
    ) -> List[EventModel]:
        """Extract events from news, mapped to given logics.

        Args:
            news_text: News article text in Chinese
            logics: List of LogicModel instances (schema)
            source: Optional source identifier

        Returns:
            List of EventModel instances (persisted to database)
        """
        if not logics:
            logger.debug("No logics provided, skipping event extraction")
            return []

        logger.info(f"Extracting events from news (source={source}, logics={len(logics)})")

        # Build logic schema JSON
        logic_schema = self._build_logic_schema(logics)

        # Call LLM
        response_json = await self._call_llm(news_text, logic_schema)

        # Parse and validate
        events = self._parse_response(response_json, logics)

        # Set metadata
        for event in events:
            event.source = source or "unknown"
            event.content_hash = self._generate_content_hash(event)

        # Persist
        persisted = await self._save_events(events)

        logger.info(f"Extracted and persisted {len(persisted)} events")
        return persisted

    def _build_logic_schema(self, logics: List[LogicModel]) -> List[Dict[str, Any]]:
        """Build logic schema JSON for prompt."""
        return [
            {
                "logic_id": l.logic_id,
                "logic_family": l.logic_family,
                "direction": l.direction.name,
                "importance_level": l.importance_level.name,
                "description": l.description,
                "keywords": l.keywords or [],
                "validity_days": l.validity_days
            }
            for l in logics
        ]

    async def _call_llm(
        self,
        news_text: str,
        logic_schema: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Call LLM for event extraction."""
        prompt = self.SYSTEM_PROMPT.format(
            logic_schema_json=json.dumps(logic_schema, ensure_ascii=False),
            news_text=news_text
        )

        try:
            response = await acompletion(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a professional A-share event extraction expert. Output ONLY valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                response_format={"type": "json_object"},
                max_tokens=3000,
            )

            content = response.choices[0].message.content
            return json.loads(content)

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM response as JSON: {e}")
            raise
        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            raise

    def _parse_response(
        self,
        response: Dict[str, Any],
        logics: List[LogicModel]
    ) -> List[EventModel]:
        """Parse LLM response into EventModel instances."""
        events = []
        logic_map = {l.logic_id: l for l in logics}

        for item in response.get("events", []):
            try:
                # Validate required fields
                if not all(k in item for k in ["logic_id", "event_date", "strength_raw"]):
                    logger.warning(f"Missing required fields in event: {item}")
                    continue

                logic_id = item["logic_id"]
                if logic_id not in logic_map:
                    logger.warning(f"Event references unknown logic: {logic_id}")
                    continue

                logic = logic_map[logic_id]

                # Parse event date
                event_date = self._parse_date(item["event_date"])
                if event_date is None:
                    logger.warning(f"Invalid event date: {item['event_date']}")
                    continue

                # Parse strength
                strength_raw = Decimal(str(item["strength_raw"]))
                if not (Decimal("0") <= strength_raw <= Decimal("1")):
                    logger.warning(f"Strength out of range: {strength_raw}")
                    continue

                # Compute validity end date
                validity_days = item.get("validity_days", logic.validity_days)
                validity_end = event_date.replace(
                    day=min(validity_end.day, (event_date.replace(month=event_date.month % 12 + 1, day=1) - timedelta(days=1)).day)
                ) if validity_days else None

                # Generate event_id
                event_id = self._generate_event_id(logic_id, event_date, item.get("headline", ""))

                event = EventModel(
                    event_id=event_id,
                    logic_id=logic_id,
                    event_date=event_date,
                    source="unknown",  # Will be set later
                    headline=item.get("headline", ""),
                    strength_raw=strength_raw,
                    direction=logic.direction,  # Inherit from logic
                    validity_start=event_date,
                    validity_end=validity_end,
                    is_expired=False,
                    fingerprint=None,  # Will be computed
                    is_duplicate=False,
                )
                events.append(event)

            except Exception as e:
                logger.warning(f"Failed to parse event: {e}, item: {item}")
                continue

        return events

    def _parse_date(self, date_str: str) -> Optional[date]:
        """Parse date string into date object."""
        formats = [
            "%Y-%m-%d",
            "%Y/%m/%d",
            "%Y 年%m 月%d 日",
        ]
        for fmt in formats:
            try:
                return datetime.strptime(date_str, fmt).date()
            except ValueError:
                continue
        return None

    def _generate_event_id(
        self,
        logic_id: str,
        event_date: date,
        headline: str
    ) -> str:
        """Generate unique event_id."""
        content = f"{logic_id}:{event_date}:{headline[:50]}"
        hash_hex = hashlib.sha256(content.encode()).hexdigest()[:16]
        return f"evt_{hash_hex}"

    def _generate_content_hash(self, event: EventModel) -> str:
        """Generate content hash for deduplication."""
        content = f"{event.source}:{event.event_date}:{event.logic_id}:{event.headline}"
        return hashlib.sha256(content.encode()).hexdigest()

    async def _save_events(self, events: List[EventModel]) -> List[EventModel]:
        """Save events to database with deduplication."""
        persisted = []

        async with async_session_maker() as session:
            for event in events:
                # Check for duplicate by fingerprint
                if event.fingerprint:
                    result = await session.execute(
                        select(EventModel).where(
                            EventModel.fingerprint == event.fingerprint
                        )
                    )
                    existing = result.scalar_one_or_none()

                    if existing:
                        logger.debug(f"Duplicate event detected: {event.fingerprint}")
                        event.is_duplicate = True
                        continue

                session.add(event)
                persisted.append(event)

            await session.commit()

        return persisted


# Import timedelta for date calculation
from datetime import timedelta
